version: "3.8"

services:
  server:
    image: craftsman:${API_VERSION}
    build:
      context: .
      dockerfile: Docker/Dockerfile
    environment:
      API_VERSION: ${API_VERSION}
      APP_VERSION: ${APP_VERSION}
