name: Formatting Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: pyproject.toml
      - name: Run ruff check
        run: |
          uv run ruff format --check --diff .