name: Unit Testing Jobs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          pyproject-file: pyproject.toml
      - name: Run tests
        run: uv run pytest
